nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/davidhrbac/ui-test/main/extensions/davidtest/0.1.0
  compressedEndpoint: >-
    https://raw.githubusercontent.com/davidhrbac/ui-test/main/extensions/davidtest/0.1.0.tgz
  noCache: false
  noAuth: false
  metadata: {}
